-- MySQL Script generated by MySQL Workbench
-- Mon Dec 12 19:12:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `signup_date` DATETIME NOT NULL,
  `activity_activity_id` INT NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL,
  `country_country_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_city_country1_idx` (`country_country_id` ASC),
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_country_id`)
    REFERENCES `mydb`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `postal code` VARCHAR(45) NULL,
  `addresscol` VARCHAR(45) NULL,
  `city_city_id` INT NOT NULL,
  `Users_user_id` INT NOT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `fk_address_city1_idx` (`city_city_id` ASC),
  INDEX `fk_address_Users1_idx` (`Users_user_id` ASC),
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `mydb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcategory` (
  `subcategory_id` INT NOT NULL AUTO_INCREMENT,
  `subcategory_name` VARCHAR(45) NOT NULL,
  `category_category_id` INT NOT NULL,
  PRIMARY KEY (`subcategory_id`, `category_category_id`),
  INDEX `fk_subcategory_category1_idx` (`category_category_id` ASC),
  CONSTRAINT `fk_subcategory_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_description` TEXT(256) NULL,
  `subcategory_subcategory_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `subcategory_subcategory_id`),
  INDEX `fk_product_subcategory1_idx` (`subcategory_subcategory_id` ASC),
  CONSTRAINT `fk_product_subcategory1`
    FOREIGN KEY (`subcategory_subcategory_id`)
    REFERENCES `mydb`.`subcategory` (`subcategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`offers` (
  `offer_id` INT NOT NULL AUTO_INCREMENT,
  `note` TEXT(128) NULL,
  `Users_user_id` INT NOT NULL,
  `product_price` DECIMAL(5,2) NOT NULL,
  `product_product_id` INT NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `out_of_stock` ENUM('true', 'false') NOT NULL,
  PRIMARY KEY (`offer_id`),
  INDEX `fk_offers_Users1_idx` (`Users_user_id` ASC),
  INDEX `fk_offers_product1_idx` (`product_product_id` ASC),
  CONSTRAINT `fk_offers_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offers_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`likeactivity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`likeactivity` (
  `likeactivity_id` INT NOT NULL AUTO_INCREMENT,
  `like_type` INT NOT NULL,
  `offers_offer_id` INT NOT NULL,
  `Users_user_id` INT NOT NULL,
  PRIMARY KEY (`likeactivity_id`),
  INDEX `fk_likeactivity_offers1_idx` (`offers_offer_id` ASC),
  INDEX `fk_likeactivity_Users1_idx` (`Users_user_id` ASC),
  CONSTRAINT `fk_likeactivity_offers1`
    FOREIGN KEY (`offers_offer_id`)
    REFERENCES `mydb`.`offers` (`offer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likeactivity_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`score_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`score_activity` (
  `score_id` INT NOT NULL,
  `score` INT NULL,
  `likeactivity_likeactivity_id` INT NOT NULL,
  `offers_offer_id` INT NOT NULL,
  `Users_user_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`score_id`),
  INDEX `fk_score_likeactivity1_idx` (`likeactivity_likeactivity_id` ASC),
  INDEX `fk_score_offers1_idx` (`offers_offer_id` ASC),
  INDEX `fk_score_Users1_idx` (`Users_user_id` ASC),
  CONSTRAINT `fk_score_likeactivity1`
    FOREIGN KEY (`likeactivity_likeactivity_id`)
    REFERENCES `mydb`.`likeactivity` (`likeactivity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_offers1`
    FOREIGN KEY (`offers_offer_id`)
    REFERENCES `mydb`.`offers` (`offer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`token` (
  `token_id` INT NOT NULL,
  `token` INT NULL,
  `Users_user_id` INT NOT NULL,
  PRIMARY KEY (`token_id`),
  INDEX `fk_token_Users1_idx` (`Users_user_id` ASC),
  CONSTRAINT `fk_token_Users1`
    FOREIGN KEY (`Users_user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shops` (
  `shop_id` INT NOT NULL AUTO_INCREMENT,
  `shop_name` VARCHAR(45) NULL,
  `shop_type` VARCHAR(45) NULL,
  PRIMARY KEY (`shop_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shops_has_offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shops_has_offers` (
  `offers_offer_id` INT NOT NULL,
  `shops_shop_id` INT NOT NULL,
  PRIMARY KEY (`offers_offer_id`, `shops_shop_id`),
  INDEX `fk_offers_has_shops_shops1_idx` (`shops_shop_id` ASC),
  INDEX `fk_offers_has_shops_offers1_idx` (`offers_offer_id` ASC),
  CONSTRAINT `fk_offers_has_shops_offers1`
    FOREIGN KEY (`offers_offer_id`)
    REFERENCES `mydb`.`offers` (`offer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offers_has_shops_shops1`
    FOREIGN KEY (`shops_shop_id`)
    REFERENCES `mydb`.`shops` (`shop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE `mydb`.`users` 
ADD COLUMN `user_type` ENUM('user', 'admin') NOT NULL AFTER `activity_activity_id`;
